// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/category/category.proto

/*
Package go_micro_service_category is a generated protocol buffer package.

It is generated from these files:
	proto/category/category.proto

It has these top-level messages:
	CategoryRequest
	CrateCategoryResponse
	UpdateCategoryResponse
	DeleteCategoryRequest
	DeleteCategoryResponse
	FindByNameRequest
	CategoryResponse
	FindByIDRequest
	FindByLevelRequest
	FindByParentRequest
	FindAllRequest
	FindAllResponse
*/
package go_micro_service_category

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 创建分类请求
type CategoryRequest struct {
	CategoryName        string `protobuf:"bytes,1,opt,name=category_name,json=categoryName" json:"category_name,omitempty"`
	CategoryLevel       uint32 `protobuf:"varint,2,opt,name=category_level,json=categoryLevel" json:"category_level,omitempty"`
	CategoryParent      int64  `protobuf:"varint,3,opt,name=category_parent,json=categoryParent" json:"category_parent,omitempty"`
	CategoryImage       string `protobuf:"bytes,4,opt,name=category_image,json=categoryImage" json:"category_image,omitempty"`
	CategoryDescription string `protobuf:"bytes,5,opt,name=category_description,json=categoryDescription" json:"category_description,omitempty"`
}

func (m *CategoryRequest) Reset()                    { *m = CategoryRequest{} }
func (m *CategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*CategoryRequest) ProtoMessage()               {}
func (*CategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CategoryRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryRequest) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryRequest) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryRequest) GetCategoryImage() string {
	if m != nil {
		return m.CategoryImage
	}
	return ""
}

func (m *CategoryRequest) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

// 创建分类响应
type CrateCategoryResponse struct {
	Message    string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	CategoryId int64  `protobuf:"varint,2,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
}

func (m *CrateCategoryResponse) Reset()                    { *m = CrateCategoryResponse{} }
func (m *CrateCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*CrateCategoryResponse) ProtoMessage()               {}
func (*CrateCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CrateCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CrateCategoryResponse) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

// 更新分类响应
type UpdateCategoryResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateCategoryResponse) Reset()                    { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()               {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 删除分类请求
type DeleteCategoryRequest struct {
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
}

func (m *DeleteCategoryRequest) Reset()                    { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()               {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteCategoryRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

// 删除分类响应
type DeleteCategoryResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteCategoryResponse) Reset()                    { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()               {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 根据分类名查找分类
type FindByNameRequest struct {
	CategoryName string `protobuf:"bytes,1,opt,name=category_name,json=categoryName" json:"category_name,omitempty"`
}

func (m *FindByNameRequest) Reset()                    { *m = FindByNameRequest{} }
func (m *FindByNameRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByNameRequest) ProtoMessage()               {}
func (*FindByNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FindByNameRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

// 返回分类信息
type CategoryResponse struct {
	Id                  int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CategoryName        string `protobuf:"bytes,2,opt,name=category_name,json=categoryName" json:"category_name,omitempty"`
	CategoryLevel       uint32 `protobuf:"varint,3,opt,name=category_level,json=categoryLevel" json:"category_level,omitempty"`
	CategoryParent      int64  `protobuf:"varint,4,opt,name=category_parent,json=categoryParent" json:"category_parent,omitempty"`
	CategoryImage       string `protobuf:"bytes,5,opt,name=category_image,json=categoryImage" json:"category_image,omitempty"`
	CategoryDescription string `protobuf:"bytes,6,opt,name=category_description,json=categoryDescription" json:"category_description,omitempty"`
}

func (m *CategoryResponse) Reset()                    { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()               {}
func (*CategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CategoryResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CategoryResponse) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryResponse) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryResponse) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryResponse) GetCategoryImage() string {
	if m != nil {
		return m.CategoryImage
	}
	return ""
}

func (m *CategoryResponse) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

type FindByIDRequest struct {
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
}

func (m *FindByIDRequest) Reset()                    { *m = FindByIDRequest{} }
func (m *FindByIDRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByIDRequest) ProtoMessage()               {}
func (*FindByIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FindByIDRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type FindByLevelRequest struct {
	Level uint32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
}

func (m *FindByLevelRequest) Reset()                    { *m = FindByLevelRequest{} }
func (m *FindByLevelRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByLevelRequest) ProtoMessage()               {}
func (*FindByLevelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FindByLevelRequest) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type FindByParentRequest struct {
	ParentId int64 `protobuf:"varint,1,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
}

func (m *FindByParentRequest) Reset()                    { *m = FindByParentRequest{} }
func (m *FindByParentRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByParentRequest) ProtoMessage()               {}
func (*FindByParentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FindByParentRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type FindAllRequest struct {
}

func (m *FindAllRequest) Reset()                    { *m = FindAllRequest{} }
func (m *FindAllRequest) String() string            { return proto.CompactTextString(m) }
func (*FindAllRequest) ProtoMessage()               {}
func (*FindAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type FindAllResponse struct {
	Category []*CategoryResponse `protobuf:"bytes,1,rep,name=category" json:"category,omitempty"`
}

func (m *FindAllResponse) Reset()                    { *m = FindAllResponse{} }
func (m *FindAllResponse) String() string            { return proto.CompactTextString(m) }
func (*FindAllResponse) ProtoMessage()               {}
func (*FindAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *FindAllResponse) GetCategory() []*CategoryResponse {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*CategoryRequest)(nil), "go.micro.service.category.CategoryRequest")
	proto.RegisterType((*CrateCategoryResponse)(nil), "go.micro.service.category.CrateCategoryResponse")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "go.micro.service.category.UpdateCategoryResponse")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "go.micro.service.category.DeleteCategoryRequest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "go.micro.service.category.DeleteCategoryResponse")
	proto.RegisterType((*FindByNameRequest)(nil), "go.micro.service.category.FindByNameRequest")
	proto.RegisterType((*CategoryResponse)(nil), "go.micro.service.category.CategoryResponse")
	proto.RegisterType((*FindByIDRequest)(nil), "go.micro.service.category.FindByIDRequest")
	proto.RegisterType((*FindByLevelRequest)(nil), "go.micro.service.category.FindByLevelRequest")
	proto.RegisterType((*FindByParentRequest)(nil), "go.micro.service.category.FindByParentRequest")
	proto.RegisterType((*FindAllRequest)(nil), "go.micro.service.category.FindAllRequest")
	proto.RegisterType((*FindAllResponse)(nil), "go.micro.service.category.FindAllResponse")
}

func init() { proto.RegisterFile("proto/category/category.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0xc6, 0x4d, 0x9b, 0x4e, 0x89, 0x13, 0xb6, 0x29, 0x32, 0x41, 0x88, 0x68, 0x11, 0x22,
	0x14, 0x30, 0xd4, 0x5c, 0xb8, 0x42, 0x23, 0x50, 0x24, 0x84, 0x90, 0x25, 0x2e, 0x5c, 0x90, 0x89,
	0x47, 0x91, 0x51, 0xfc, 0xd3, 0xb5, 0x29, 0xe2, 0x69, 0x78, 0x35, 0x5e, 0x81, 0x37, 0x40, 0xd9,
	0xcd, 0xae, 0xe3, 0xc4, 0x75, 0x6c, 0x6e, 0xd9, 0xd9, 0x6f, 0xe6, 0x9b, 0x6f, 0x67, 0xbe, 0x18,
	0xee, 0x27, 0x3c, 0xce, 0xe2, 0x17, 0x73, 0x2f, 0xc3, 0x45, 0xcc, 0x7f, 0xe9, 0x1f, 0xb6, 0x88,
	0xd3, 0xbb, 0x8b, 0xd8, 0x0e, 0x83, 0x39, 0x8f, 0xed, 0x14, 0xf9, 0x75, 0x30, 0x47, 0x5b, 0x01,
	0xd8, 0x1f, 0x02, 0xfd, 0xcb, 0xf5, 0xc1, 0xc5, 0xab, 0x1f, 0x98, 0x66, 0xf4, 0x21, 0xf4, 0xd4,
	0xfd, 0xd7, 0xc8, 0x0b, 0xd1, 0x22, 0x63, 0x32, 0x39, 0x76, 0x6f, 0xa9, 0xe0, 0x47, 0x2f, 0x44,
	0xfa, 0x08, 0x4c, 0x0d, 0x5a, 0xe2, 0x35, 0x2e, 0xad, 0xf6, 0x98, 0x4c, 0x7a, 0xae, 0x4e, 0xfd,
	0xb0, 0x0a, 0xd2, 0xc7, 0xd0, 0xd7, 0xb0, 0xc4, 0xe3, 0x18, 0x65, 0x96, 0x31, 0x26, 0x13, 0xc3,
	0xd5, 0xd9, 0x9f, 0x44, 0xb4, 0x50, 0x2f, 0x08, 0xbd, 0x05, 0x5a, 0x07, 0x82, 0x55, 0xd7, 0x9b,
	0xad, 0x82, 0xf4, 0x02, 0x86, 0x1a, 0xe6, 0x63, 0x3a, 0xe7, 0x41, 0x92, 0x05, 0x71, 0x64, 0x75,
	0x04, 0xf8, 0x54, 0xdd, 0x4d, 0xf3, 0x2b, 0xe6, 0xc2, 0xd9, 0x25, 0xf7, 0x32, 0xcc, 0x65, 0xa6,
	0x49, 0x1c, 0xa5, 0x48, 0x2d, 0x38, 0x0a, 0x31, 0x4d, 0x57, 0x5c, 0x52, 0xa1, 0x3a, 0xd2, 0x07,
	0x70, 0x92, 0x37, 0xe3, 0x0b, 0x65, 0x86, 0x0b, 0xba, 0x13, 0x9f, 0x39, 0x70, 0xe7, 0x73, 0xe2,
	0x37, 0x2a, 0xca, 0x5e, 0xc3, 0xd9, 0x14, 0x97, 0xb8, 0x99, 0x23, 0xdf, 0x7b, 0x8b, 0x8d, 0x94,
	0xb1, 0x6d, 0x67, 0xd6, 0x60, 0xbb, 0xfd, 0x2e, 0x88, 0xfc, 0xb7, 0x62, 0x5a, 0x4d, 0x26, 0xcb,
	0xfe, 0x12, 0x18, 0xec, 0x10, 0x99, 0xd0, 0xd6, 0xad, 0xb5, 0x03, 0x7f, 0xb7, 0x52, 0xbb, 0xd6,
	0x8e, 0x18, 0x35, 0x77, 0xe4, 0xa0, 0xe6, 0x8e, 0x74, 0x9a, 0xec, 0xc8, 0xe1, 0xcd, 0x3b, 0xe2,
	0x40, 0x5f, 0xbe, 0xd6, 0x6c, 0x5a, 0x7b, 0x2a, 0xe7, 0x40, 0x65, 0x8e, 0x50, 0xa1, 0xd2, 0x86,
	0xd0, 0x91, 0x52, 0x89, 0x90, 0x2a, 0x0f, 0xcc, 0x81, 0x53, 0x89, 0x95, 0x4a, 0x14, 0xf8, 0x1e,
	0x1c, 0x4b, 0xc1, 0x39, 0x43, 0x57, 0x06, 0x66, 0x3e, 0x1b, 0x80, 0xb9, 0xca, 0x79, 0xb3, 0x54,
	0xb5, 0xd9, 0x17, 0xd9, 0xa5, 0x88, 0xac, 0xe7, 0xf2, 0x1e, 0xba, 0xaa, 0x25, 0x8b, 0x8c, 0x8d,
	0xc9, 0x89, 0xf3, 0xd4, 0xbe, 0xd1, 0xed, 0xf6, 0xf6, 0x58, 0x5d, 0x9d, 0xec, 0xfc, 0x3e, 0x82,
	0xae, 0xba, 0xa6, 0x31, 0xf4, 0x0a, 0x96, 0xa1, 0xe7, 0xb5, 0x8a, 0x8a, 0x2e, 0x47, 0x2f, 0xab,
	0xb0, 0x65, 0x46, 0x64, 0x2d, 0x7a, 0x05, 0x66, 0xd1, 0x4f, 0x8d, 0x18, 0x2f, 0x2a, 0xb0, 0xe5,
	0x36, 0x65, 0x2d, 0xfa, 0x13, 0xcc, 0xa2, 0xa9, 0x68, 0x55, 0xe3, 0xa5, 0xce, 0xad, 0x24, 0x2e,
	0x77, 0xac, 0xd0, 0x2a, 0xf6, 0x46, 0xdd, 0x48, 0x87, 0xd2, 0x67, 0x15, 0xa5, 0x76, 0x8c, 0x3c,
	0x6a, 0x32, 0x64, 0xd6, 0xa2, 0x21, 0x0c, 0x8a, 0x94, 0xb3, 0x69, 0xe5, 0x03, 0x6f, 0x79, 0xa1,
	0x29, 0x1d, 0x97, 0xdb, 0x9e, 0xd3, 0x49, 0x9f, 0x3f, 0xdf, 0xcb, 0xb8, 0xe9, 0xa4, 0xd1, 0xbe,
	0x06, 0x37, 0x6c, 0xc0, 0x5a, 0x34, 0x83, 0x61, 0x91, 0x73, 0xfd, 0x9f, 0x61, 0xef, 0x25, 0x2d,
	0x58, 0xb2, 0x21, 0xeb, 0x77, 0xed, 0x48, 0xbd, 0x45, 0x4f, 0xea, 0x14, 0xf8, 0x0f, 0xae, 0x6f,
	0x87, 0xe2, 0x63, 0xfe, 0xea, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x07, 0xa1, 0x74, 0xed,
	0x07, 0x00, 0x00,
}
