// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/category/category.proto

package go_micro_service_category

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Category service

func NewCategoryEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Category service

type CategoryService interface {
	CrateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*CrateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*UpdateCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...client.CallOption) (*DeleteCategoryResponse, error)
	FindCategoryByName(ctx context.Context, in *FindByNameRequest, opts ...client.CallOption) (*CategoryResponse, error)
	FindCategoryByID(ctx context.Context, in *FindByIDRequest, opts ...client.CallOption) (*CategoryResponse, error)
	FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, opts ...client.CallOption) (*FindAllResponse, error)
	FindCategoryByParent(ctx context.Context, in *FindByParentRequest, opts ...client.CallOption) (*FindAllResponse, error)
	FindAllCategory(ctx context.Context, in *FindAllRequest, opts ...client.CallOption) (*FindAllResponse, error)
}

type categoryService struct {
	c    client.Client
	name string
}

func NewCategoryService(name string, c client.Client) CategoryService {
	return &categoryService{
		c:    c,
		name: name,
	}
}

func (c *categoryService) CrateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*CrateCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "Category.CrateCategory", in)
	out := new(CrateCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) UpdateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*UpdateCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "Category.UpdateCategory", in)
	out := new(UpdateCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...client.CallOption) (*DeleteCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "Category.DeleteCategory", in)
	out := new(DeleteCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindCategoryByName(ctx context.Context, in *FindByNameRequest, opts ...client.CallOption) (*CategoryResponse, error) {
	req := c.c.NewRequest(c.name, "Category.FindCategoryByName", in)
	out := new(CategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindCategoryByID(ctx context.Context, in *FindByIDRequest, opts ...client.CallOption) (*CategoryResponse, error) {
	req := c.c.NewRequest(c.name, "Category.FindCategoryByID", in)
	out := new(CategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, opts ...client.CallOption) (*FindAllResponse, error) {
	req := c.c.NewRequest(c.name, "Category.FindCategoryByLevel", in)
	out := new(FindAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindCategoryByParent(ctx context.Context, in *FindByParentRequest, opts ...client.CallOption) (*FindAllResponse, error) {
	req := c.c.NewRequest(c.name, "Category.FindCategoryByParent", in)
	out := new(FindAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindAllCategory(ctx context.Context, in *FindAllRequest, opts ...client.CallOption) (*FindAllResponse, error) {
	req := c.c.NewRequest(c.name, "Category.FindAllCategory", in)
	out := new(FindAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Category service

type CategoryHandler interface {
	CrateCategory(context.Context, *CategoryRequest, *CrateCategoryResponse) error
	UpdateCategory(context.Context, *CategoryRequest, *UpdateCategoryResponse) error
	DeleteCategory(context.Context, *DeleteCategoryRequest, *DeleteCategoryResponse) error
	FindCategoryByName(context.Context, *FindByNameRequest, *CategoryResponse) error
	FindCategoryByID(context.Context, *FindByIDRequest, *CategoryResponse) error
	FindCategoryByLevel(context.Context, *FindByLevelRequest, *FindAllResponse) error
	FindCategoryByParent(context.Context, *FindByParentRequest, *FindAllResponse) error
	FindAllCategory(context.Context, *FindAllRequest, *FindAllResponse) error
}

func RegisterCategoryHandler(s server.Server, hdlr CategoryHandler, opts ...server.HandlerOption) error {
	type category interface {
		CrateCategory(ctx context.Context, in *CategoryRequest, out *CrateCategoryResponse) error
		UpdateCategory(ctx context.Context, in *CategoryRequest, out *UpdateCategoryResponse) error
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, out *DeleteCategoryResponse) error
		FindCategoryByName(ctx context.Context, in *FindByNameRequest, out *CategoryResponse) error
		FindCategoryByID(ctx context.Context, in *FindByIDRequest, out *CategoryResponse) error
		FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, out *FindAllResponse) error
		FindCategoryByParent(ctx context.Context, in *FindByParentRequest, out *FindAllResponse) error
		FindAllCategory(ctx context.Context, in *FindAllRequest, out *FindAllResponse) error
	}
	type Category struct {
		category
	}
	h := &categoryHandler{hdlr}
	return s.Handle(s.NewHandler(&Category{h}, opts...))
}

type categoryHandler struct {
	CategoryHandler
}

func (h *categoryHandler) CrateCategory(ctx context.Context, in *CategoryRequest, out *CrateCategoryResponse) error {
	return h.CategoryHandler.CrateCategory(ctx, in, out)
}

func (h *categoryHandler) UpdateCategory(ctx context.Context, in *CategoryRequest, out *UpdateCategoryResponse) error {
	return h.CategoryHandler.UpdateCategory(ctx, in, out)
}

func (h *categoryHandler) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, out *DeleteCategoryResponse) error {
	return h.CategoryHandler.DeleteCategory(ctx, in, out)
}

func (h *categoryHandler) FindCategoryByName(ctx context.Context, in *FindByNameRequest, out *CategoryResponse) error {
	return h.CategoryHandler.FindCategoryByName(ctx, in, out)
}

func (h *categoryHandler) FindCategoryByID(ctx context.Context, in *FindByIDRequest, out *CategoryResponse) error {
	return h.CategoryHandler.FindCategoryByID(ctx, in, out)
}

func (h *categoryHandler) FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, out *FindAllResponse) error {
	return h.CategoryHandler.FindCategoryByLevel(ctx, in, out)
}

func (h *categoryHandler) FindCategoryByParent(ctx context.Context, in *FindByParentRequest, out *FindAllResponse) error {
	return h.CategoryHandler.FindCategoryByParent(ctx, in, out)
}

func (h *categoryHandler) FindAllCategory(ctx context.Context, in *FindAllRequest, out *FindAllResponse) error {
	return h.CategoryHandler.FindAllCategory(ctx, in, out)
}
